# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: main
env:
  GlobVAR: ${{ github.sha }}

jobs: 
  testjob:
    env:
      VAR1JOB1: var1j1
      VAR2J1: var2j1
    runs-on: ubuntu-latest
    steps:
      - name:  job task before clone
        run: ls -la
      
      - name: first task
        run: |
          echo "Hello from j1 variable: ${{ env.VAR1JOB1 }} and ${{ env.VAR2J1 }}"
          echo "glob var: ${{ env.GlobVAR }}"
        
      
      - uses: actions/checkout@v1
      
      - name:  job task after clone
        run: ls -la
        
  depjob:
    needs: [testjob]
    runs-on: ubuntu-latest 
    steps:
      - name: second job task
        run: ls -la
        
    
  
    
