# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: main

jobs:
  testjob:
    runs-on: ubuntu-latest

    steps:
      - name: first task
        run: echo Hello from first job
      - uses: actions/checkout@v1

  depjob:
    needs: [testjob]
    runs-on: ubuntu-latest 
    steps:
      - name: second job task
        run: ls -la
        
    
  
    
