name: First Workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-slim
    steps:
      - name: Print greeting
        run: echo "Hello World"
      - name: Pring goodbye
        run: echo "Good Bye"
      - name: mutltiple line 
        run: |
          echo "line 1 pringint"
          echo "line 2 pringint"
          
